apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: epeq7e3mr-nodejs
  janus-idp.io/tekton: epeq7e3mr-nodejs
  backstage.io/kubernetes-id: epeq7e3mr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: epeq7e3mr-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
