apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: epeq7e3mr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: epeq7e3mr-nodejs 
  name: epeq7e3mr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: epeq7e3mr-nodejs 
